version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      #- pip3 install awscli
      #- pip3 install aws-sam-cli
      #- apt install -y nodejs
      #- apt install -y npm
      - pip install pytoml
      - npm install -g pnpm
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      #- npm run test
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      #- git clone https://github.com/eliaszoo/docs.git
      #- cp -rf docs/_docs/. _docs/
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      #- sam build
      #- sam deploy
      - sh ./build.sh
      #- aws cloudformation package --template template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-wzxzs8p08pkk --output-template-file template-export.yml --debug
artifacts:
  files:
    #- template-export.yml