version = 0.1
[default.deploy.parameters]
stack_name = "spreading"
resolve_s3 = true
s3_prefix = "spreading"
region = "ap-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []