version = 0.1

[default.deploy.parameters]
stack_name = "spreading_workspace_site1"
resolve_s3 = true
s3_prefix = "zego-spreading"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
