AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spreading

Globals:
  Function:
    Timeout: 10

Resources:
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./sh
      MemorySize: 256
      Handler: run.sh
      Runtime: nodejs16.x
      Role: arn:aws:iam::432303926625:role/to_spreading_codebuild2
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_ENABLE_COMPRESSION: true
          RUST_LOG: info
          PORT: 8000
          MY_BUCKET_NAME: zego-spreading-test
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:16
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      BuildMethod: makefile

Outputs:
  NextFunctionURL:
    Description: "API Gateway endpoint URL for Next.js"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  ApiId:
    Description: "Api Id"
    Value: !Sub ${ServerlessHttpApi}