AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spreading

Globals:
  Function:
    Timeout: 2

Resources:
  NextApiGateWay:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Domain:
        DomainName: spreading.io
        CertificateArn: arn:aws:acm:ap-southeast-1:547537176727:certificate/3737d1ce-54b7-411f-9e2b-659781a8e7a8
        BasePath: /
        EndpointConfiguration: REGIONAL
      DefinitionBody:
        swagger: "2.0"
        info:
          title: My API
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 256
      Handler: run.sh
      Runtime: nodejs16.x
      Role: arn:aws:iam::547537176727:role/to_spreading_codebuild
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_ENABLE_COMPRESSION: true
          RUST_LOG: info
          PORT: 8000
          MY_BUCKET_NAME: zego-spreading
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:16
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref NextApiGateWay
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: makefile

Outputs:
  MyCustomDomainName:
    Value: !Ref NextApiGateWay
    ExportName: test.spreading.io