AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-nextjs-demo

  Sample SAM Template for serverless-nextjs-demo

Globals:
  Function:
    Timeout: 10

Resources:
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 512
      Handler: run.sh
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_ENABLE_COMPRESSION: true
          RUST_LOG: info
          PORT: 8000
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:16
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      BuildMethod: makefile


Outputs:
  NextFunctionURL:
    Description: "API Gateway endpoint URL for Next.js"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"

