AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spreading

Globals:
  Function:
    Timeout: 10

Resources:
  NextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 256
      Handler: run.sh
      Runtime: nodejs16.x
      Role: arn:aws:iam::547537176727:role/to_spreading_codebuild
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_ENABLE_COMPRESSION: true
          RUST_LOG: info
          PORT: 8000
          MY_BUCKET_NAME: zego-spreading
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:16
      Events:
        HttpEvent:
          Type: HttpApi
<<<<<<< HEAD
      VpcConfig:
        SecurityGroupIds:
          - sg-01740868fe8f300ff
        SubnetIds:
          - subnet-03e38aa3f7292ff8b
          - subnet-0d7552b23eb723532
      FileSystemConfigs:
        Arn: arn:aws:elasticfilesystem:ap-southeast-1:547537176727:access-point/fsap-006bc3bc25155b68b
        LocalMountPath: /mnt/efs
=======
>>>>>>> 153bcc64fcd6ee42fe5a25cc1110b34c7a75a577
    Metadata:
      BuildMethod: makefile


Outputs:
  NextFunctionURL:
    Description: "API Gateway endpoint URL for Next.js"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  ApiId:
    Description: "Api Id"
    Value: !Sub ${ServerlessHttpApi}